### ISSUE TITLE
Support for populate

### ISSUE THREAD

**Issue by Prinzhorn** [mongoosejs/mongoose-text-search#1]
Given that this will sooner or later land in Mongoose, will things like `populate` be available then?

Do you have any thoughts on how to handle the meta data that the text command returns (per object like `score` or per query like `stats`)?

Edit: I don't know much about the internals of Mongoose (query interface etc.) but from the top of my Head I'd love to do this:

``` js
Post.find({foo: 'bar'}).text('kitten').populate('comments').exec(function(err, posts) {

});
```

If `text` is used with a String of length > 0 Mongoose uses the `text` command internally and passes the options of `find` as the `filter` property. `sort` is then of course ignored. But `limit` on the other hand can then be passed to the text command as well.

**Comment by aheckmann** [comment]
I'm not ignoring this, just nowhere near a computer so can't speak to the
meta data.

Re population: you can pass docs to Model.populate manually in mongoose
3.6. I don't plan on adding population to this repo. Once in mongoose then
yes we'll have it.

On Saturday, April 20, 2013, Alexander Prinzhorn wrote:

> Given that this will sooner or later land in Mongoose, will things like
> populate be available then?
> 
> Do you have any thoughts on how to handle the meta data that the text
> command returns (per object like score or per query like stats)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aheckmann/mongoose-text-search/issues/1
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann

**Comment by Prinzhorn** [comment]
> Re population: you can pass docs to Model.populate manually in mongoose 3.6. I don't plan on adding population to this repo. Once in mongoose then yes we'll have it.

Sounds good.

**Comment by palominoz** [comment]
+1
