### ISSUE TITLE
Allow passing an object

### ISSUE THREAD

**Issue by Prinzhorn** [mongoosejs/mongoose-text-search#2]
Currently the only thing that can be passed is a string which will be used as the `search` property for the `text` command. Things like `filter`, `project` or `limit` aren't possible. Similar question than #1: Are there plans to make this more Mongoose-like?

**Comment by aheckmann** [comment]
Read the docs again.

**Comment by Prinzhorn** [comment]
Well, that was embarrassing :confused:

**Comment by aheckmann** [comment]
:)

On Saturday, April 20, 2013, Alexander Prinzhorn wrote:

> Well, that was embarrassing [image: :confused:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aheckmann/mongoose-text-search/issues/2#issuecomment-16704834
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
