### ISSUE TITLE
mongoose-text-search on existing DB

### ISSUE THREAD

**Issue by scognaman** [mongoosejs/mongoose-text-search#3]
I have some difficult if I want apply the example code in an existing db.
Following your example i've write this code:

``` js
var url = require("url");
var express = require("express");
var app = express();      

app.get("/", function(request, response, next) {
    response.header("Access-Control-Allow-Origin", "*");

                var mongoose = require('mongoose');
                mongoose.connect('localhost', 'blomming');

                var textSearch = require('mongoose-text-search');                   

                var blommingSchema = mongoose.Schema({
                    name: String,
                    description: [String],
                    url: String,
                    price: String,
                    original_price: String,
                    currency: String,
                    photos: [{
                        first:String,
                        second:String
                    }],
                    quantity: String,
                    fbcomments: String,
                    shop: [{
                        id:String,
                        url:String,
                        items_url:String,
                        name:String,
                        image:String
                    }],

                });

                blommingSchema.plugin(textSearch);               
                blommingSchema.index({ description : 'text' });               
                var blommingDoc = mongoose.model('products', blommingSchema);

    var options = {
       limit: 10
    }

    blommingDoc.textSearch('specchio',options, function (err, output) {
        if (err) throw err;
        console.log(output);
        return response.send(JSON.stringify({"success" : true, "data" : output}));
        return response.end();
    });

});

app.listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```

I've runned a debug step by step and the problem is this.
If I use a callback similar to "Game.create({ name: 'Super Mario 64', tags: ['nintendo', 'mario', '3d'] }, function (err) {"  the debug enter inside a function blommingDoc.textSearch. If I don't use this it doesn't enter inside. But i don't need to create stuff each time that i want to search something.
Also on your example code if I comment the create function the debug jump over and doesn't reach the textSearch function.
I'm a newbie of nodejs and mongodb so i'm sorry if the solution is trivial.
Could you help me ?
Thanks.

**Comment by aheckmann** [comment]
A few things:

1) you don't want to create a new connection for every request. This is slow and wastes resources. Open the connection with mongoose and define your schema and model once when you start the application, then use the model within your route.

2) when you shut down your app, also close the mongoose connection `mongoose.disconnect()`.

3) As for the debug issue, I think you're struggling with the async nature of I/O in node.js. In the example, the text search runs within the callback of the create() call so order matters.
