### ISSUE TITLE
textSearch hangs forever when searching a model with no records

### ISSUE THREAD

**Issue by mathisonian** [mongoosejs/mongoose-text-search#4]
e.g.

``` js
  search: function(req, res, next) {
    MyModel.textSearch(req.params.searchstring, function(err, output) {
      if(err) {
        console.log(err);
      }
      res.json(_.map(output.results, function(r) {return r.obj} ));
    })
  }
```

will output no error string and never return if MyModel doesn't have any records.

Using:

```
mongoose@3.5.16
mongoose-text-search@0.0.2
```

```
$ mongod --version
db version v2.4.6

$ node --version
v0.10.17
```

**Comment by aheckmann** [comment]
Does it hang if run in the mongodb console? If not, does it hang if run
with just the node driver?

mongodb, node, mongoose, and plugin versions please.

On Friday, September 27, 2013, Matthew Conlen wrote:

> e.g.
> 
>   search: function(req, res, next) {
>     MyModel.textSearch(req.params.searchstring, function(err, output) {
>       if(err) {
>         console.log(err);
>       }
>       res.json(_.map(output.results, function(r) {return r.obj} ));
>     })
>   }
> 
> will output no error string and never return if MyModel doesn't have any
> records
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aheckmann/mongoose-text-search/issues/4
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by mathisonian** [comment]
Added the versions to the original post.

From the `mongo` console:

```
db.modelname.runCommand("text", {search: "searchterm"})
{
    "queryDebugString" : "searchterm||||||",
    "language" : "english",
    "results" : [ ],
    "stats" : {
        "nscanned" : 0,
        "nscannedObjects" : 0,
        "n" : 0,
        "nfound" : 0,
        "timeMicros" : 9281
    },
    "ok" : 1
}
```

Returns correctly. Will check using node driver

**Comment by frty2** [comment]
I have a similar problem. No result, no error, etc... even with data in the collection.

Using the mongo cmd I get the error "too many text index for: ..", even if i don't create an index on the collection. Is there some sort of auto text index creation for mongoose?

Why is this error not passed to the callback?

**Comment by feaber** [comment]
The problem with forever hangs is that callback function is never executed and You probably return nothing to the browser.

As far as I investigated the problem can be related with recent changes in mongodb project:
./mongodb/lib/mongodb/db.js

in:Db.prototype.command function

**Comment by aheckmann** [comment]
can't reproduce this.

@frty2 yes mongoose auto-creates indexes when you call `var m = mongoose.model(X, schema)`. You can listen for errors with `m.on('index', callback)`.

@feaber interesting. i'm aware of some poor error swallowing behavior by the driver. not sure if its been fixed yet.

I'm going to close unless there's more to go on. If you can reliably reproduce, please submit more information or better yet, a pull request with the fix and a test.

**Comment by matejkramny** [comment]
issue could be that the text search isn't enabled on your mongo.. Wasn't on mine, and was hanging forever..

**Comment by feaber** [comment]
Nah, it was my code :(
I was connecting / closing connection in every action.
When I test with "var db = mongoose.connect(mongo_uri);" on top of main js file, it started to work.
Looks like textSearch when is execuded had no valid connection.
The db driver will not run callback if there is no connection.

I think I have to read more about proper handling db connections in node.js :)

Regards,
Konrad.
