### ISSUE TITLE
Index document and a linked doc together

### ISSUE THREAD

**Issue by srour** [mongoosejs/mongoose-text-search#6]
Is there a way of indexing a document and linked document together?

For example, i have a schema "movie" with keywords in it but they are modeled as separate documents and referenced from movies. When i search i want the keyword metadata (name) to be included in the index. 

Is this possible with this module?

**Comment by aheckmann** [comment]
What is a linked document?

Could you provide some example schemas so I can get a better idea of what you are asking?
